set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind C-t send-prefix

set -g mouse on
setw -g mode-keys vi
set-option -g set-clipboard on

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"

bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -selection clipboard"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H previous-window
bind L next-window

bind -n M-h previous-window
bind -n M-l next-window

unbind '"'
unbind %

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

unbind r
bind r source-file ~/.tmux.conf

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# set -g @plugin "nordtheme/tmux"

# set -g @plugin 'catppuccin/tmux'

# set -g @catppuccin_flavour 'mocha'
# set -g @catppuccin_window_number_position "left"
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_status_enable "yes"

set -g @plugin 'dracula/tmux'

# set -g @dracula-colors "
# red_lightest='#ff6b6b'
# red_light='#e84142'
# red='#c41e3d'
# red_dark='#9b1d30'
# red_darkest='#6b0015'
# "

set -g @dracula-show-powerline true
set -g @dracula-plugins "battery cpu-usage ram-usage time"
set -g @dracula-show-timezone false
set -g @dracula-battery-label "🦇 "
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

set -g @dracula-cpu-usage-colors "cyan dark_gray"
set -g @dracula-ram-usage-colors "dark_purple white"
set -g @dracula-battery-colors "pink dark_gray"
set -g @dracula-time-colors "orange dark_gray"

set -g @dracula-refresh-rate 1

# run '~/.tmux/plugins/tmux/nord.tmux'
run '~/.tmux/plugins/tpm/tpm'
